---
- name: Add user to AD group
  hosts: all
  gather_facts: no
  vars:
    domain_name: "mcahome.local"
    username: "mkoan"
    target_group: "RootUsers"
  tasks:
    - name: Add user to group
      microsoft.ad.group:
        # 'name' parametresi, grup bulunamadığında yeni bir grup oluşturmak için kullanılır.
        name: "{{ target_group }}"
        identity: "{{ target_group }}"
        members:
          add:
            # Çoklu domain ortamlarında, kullanıcı adını domain ile birlikte belirtmek en iyisidir.
            - "{{ username }}@{{ domain_name }}"
        state: present
        domain_server: "AD01.{{ domain_name }}"
        domain_username: "administrator@{{ domain_name }}" # Veya başka bir yetkili kullanıcı
        domain_password: "{{ ad_admin_password }}"
##### These vars must be defined in template
# ansible_connection: winrm
# ansible_winrm_server_cert_validation: ignore
# ansible_port: 5985
# ansible_winrm_transport: ntlm