---
- name: Add user to AD group
  hosts: all
  gather_facts: no
  vars:
    #domain_name: "mcahome.local"
    username: "mkoan"
    target_group: "RootUsers"
  tasks:
    - name: Add user to group
      microsoft.ad.group:
        identity: "{{ target_group }}"
        members:
          add:
            - "{{ username }}"
        state: present
        domain_server: AD01.mcahome.local
##### These vars must be defined in template
# ansible_connection: winrm
# ansible_winrm_server_cert_validation: ignore
# ansible_port: 5985
# ansible_winrm_transport: ntlm